name: PR Label Checklists

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize, edited]

jobs:
  verify:
    name: Verify
    permissions:
      statuses: write
      contents: read
    uses: sashacmc/ci/.github/workflows/pr-label-checklists-verify.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
